### PR TITLE
Update compatibility with pynamodb 5.0 and bump 0.3.0

### PR DESCRIPTION
**Pull request by fsouza**
Doing this in a "rip the band-aid" fashion. Let me know if we should change the code to keep supporting pynamodb <5.0.0.

### CODE REVIEW

**Review by garrettheel — DISMISSED** [review]

**Comment by fsouza** [comment]
Oh just noticed `make lint` is actually failing. Will investigate and fix. Also travis isn't running anymore? One more project to migrate to GHA x)

**Comment by garrettheel** [comment]
Let me look into travis. I didn't turn it off for this repo yet

**Review by ikonst — DISMISSED** [review]

**Review by garrettheel — DISMISSED** [review]

File: .github/workflows/test.yaml [hunk 1]
```diff
@@ -0,0 +1,49 @@
...
+    branches:
+      - master
+
+jobs:
+  test:
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        python-version:
+          - "3.8"
```
Comment (fsouza) [inline .github/workflows/test.yaml:15]: Added this here just because I'm planning to work on python 3.9 support next. I can also not have the matrix if preferred.

File: .github/workflows/test.yaml [hunk 2]
```diff
@@ -0,0 +1,49 @@
...
+          python-version: ${{ matrix.python-version }}
+
+      - name: install deps
+        run: |
+          python -m pip install -e . -r requirements.txt
+
+      - name: run tests
+        run: make test
+
+  lint:
```
Comment (fsouza) [inline .github/workflows/test.yaml:37]: This is running pretty quickly, but if it slows down we could cache `~/.cache/pre-commit`.

**Review by garrettheel — APPROVED** [review]

File: .github/workflows/test.yaml (hunk 1 above)
Comment (fsouza) [reply .github/workflows/test.yaml:15]: for reference, this is the current issue with 3.9:

```
self = <pynamodb_attributes.unicode_delimited_tuple.UnicodeDelimitedTupleAttribute object at 0x10ddb2cd0>, value = 'US.San Francisco.94107'
    def deserialize(self, value: str) -> T:
        fields = getattr(self.tuple_type, '_fields', None)
        field_types = getattr(self.tuple_type, '_field_types', None)
        if fields and field_types:
            values = value.split(self.delimiter, maxsplit=len(fields))
            return self.tuple_type(**{f: field_types[f](v) for f, v in zip(fields, values)})
        else:
>           return self.tuple_type(value.split(self.delimiter))
E           TypeError: <lambda>() missing 1 required positional argument: 'city'
pynamodb_attributes/unicode_delimited_tuple.py:48: TypeError
```

_field_types is gone: https://bugs.python.org/issue40182
